# Generated by Django 2.2 on 2021-03-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release',
            field=models.DateField(),
        ),
    ]
